### ISSUE TITLE
ABORT THROWN BY INTERNAL EXCEPTION: Attempted to access index 0 within vector of size 0

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb-fuzzer#224]
Issue found by me running DuckFuzz locally.

### To Reproduce
```sql
CREATE TABLE integers(i INTEGER);
FROM integers AS t2(c1) WHERE COLUMNS(* EXCLUDE (c1));

```

### Error Message
```
ABORT THROWN BY INTERNAL EXCEPTION: Attempted to access index 0 within vector of size 0
```

**Comment by yacouba-kone** [comment]
Hi Mytherin,
I 've  same issue when trying to create Index.
InternalException: INTERNAL Error: Attempted to access index 167 within vector of size 167

**Comment by EricSoroos** [comment]
I'm hitting something similar with a pretty obnoxious query to unnest some json. 

```
D   select
>     "@id",
>     "UID",
>     'default' as scale,
>     image.download as url,
>     image.height as height,
>     image.width as width,
>     image['content-type'] as content_type,
>     image.filename as filename,
>     image.size as size
>   from organizations where image is not null
> 
>   union
>     select 
>       "@id",
>       "UID",
>       scale,
>       unnest(struct_),
>       '' as content_type,
>       '' as filename,
>       0::int64 as size
>     from (
>       unpivot (select "@id", "UID", unnest(image.scales) from organizations where image is not null)
>       on
>         great,
>         huge,
>         icon,
>         large,
>         larger,
>         mini,
>         preview,
>         teaser,
>         thumb,
>         tile
>       into
>       name scale
>       value struct_
>     )
> ;
Error: INTERNAL Error: Attempted to access index 7 within vector of size 7
D 
```

Each half of the query returns appropriate data. 

(note -- data is somewhat sensitive, so I'd have to redact if you need it for a test case)

**Comment by carlopi** [comment]
I think this issues has been solved since, latest master gives:
```
Error: Parser Error: COLUMNS expansion resulted in empty set of columns
```
that seems to me to be the right behaviour here.

(also, in the answer body line separator are '\r\n' that not the '\n' the parser expect, so the manual handling)

**Comment by carlopi** [comment]
@yacouba-kone and @EricSoroos: issue on the repo [duckdb/duckdb](https://github.com/duckdb/duckdb/issues) are very welcome.

This repo content is mostly bot-generated, and it's not actively monitored.
